#!/usr/bin/env python3
"""Initialize a repo-compatible skill skeleton."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import date
from pathlib import Path

from projection_support import parse_platforms, projection_dir, copy_projection


SKILL_TEMPLATE = """---
name: {name}
description: >
  {description}
---

# {display_name}

Replace this draft with the real skill instructions.

## Outputs

- Describe what the skill produces.

## When Not To Use

- Describe at least one nearby case that should not trigger the skill.

## Workflow

1. Capture intent and examples.
2. Decide which reusable files belong in `references/`, `scripts/`, or `assets/`.
3. Write or revise the skill package.
4. Validate before broader evaluation.

## Example Prompts

- Add realistic trigger examples here.
"""


CHANGELOG_TEMPLATE = """# Changelog

All notable changes to this skill will be documented in this file.
This project adheres to [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) and [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [{version}] - {date}

### Added
- Initial scaffold generated by `skill-lifecycle-manager`.
"""


def normalize_name(raw: str) -> str:
    value = raw.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-{2,}", "-", value).strip("-")
    if not value:
        raise ValueError("skill name resolves to an empty value")
    return value


def title_case(name: str) -> str:
    return " ".join(part.capitalize() for part in name.split("-"))


def parse_csv(raw: str) -> list[str]:
    return [part.strip() for part in raw.split(",") if part.strip()]


def unique_items(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            result.append(item)
    return result


def default_author() -> str:
    for env_name in ["SKILL_AUTHOR", "GIT_AUTHOR_NAME", "USER", "USERNAME"]:
        value = os.environ.get(env_name, "").strip()
        if value:
            return value
    return "Unknown Author"


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf8")


def ensure_new_dir(path: Path) -> None:
    if path.exists():
        raise FileExistsError(f"{path} already exists")
    path.mkdir(parents=True, exist_ok=False)


def build_skill_json(
    name: str,
    display_name: str,
    description: str,
    version: str,
    maturity: str,
    categories: list[str],
    author: str,
    tags: list[str],
) -> dict:
    return {
        "schemaVersion": 1,
        "name": name,
        "displayName": display_name,
        "description": description,
        "version": version,
        "maturity": maturity,
        "categories": categories,
        "tags": tags,
        "authors": [{"name": author}],
        "entrypoints": {"skillDoc": "SKILL.md", "changelog": "CHANGELOG.md"},
        "capabilities": {
            "shell": True,
            "network": False,
            "filesystemRead": True,
            "filesystemWrite": True,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a repo-compatible skill scaffold.")
    parser.add_argument("skill_name", help="Skill name; normalized to kebab-case")
    parser.add_argument("--path", required=True, help="Directory that will contain the new skill folder")
    parser.add_argument("--description", required=True, help="One-line trigger description for skill.json and frontmatter")
    parser.add_argument("--display-name", help="Human-facing display name")
    parser.add_argument("--version", default="0.1.0")
    parser.add_argument("--maturity", default="experimental", choices=["experimental", "beta", "stable", "deprecated"])
    parser.add_argument("--categories", default="workflow", help="Comma-separated categories from categories.json")
    parser.add_argument(
        "--tags",
        help="Optional comma-separated tags. Defaults to the skill name plus categories.",
    )
    parser.add_argument("--resources", default="references,scripts", help="Comma-separated resource dirs to create")
    parser.add_argument("--author", default=default_author())
    parser.add_argument("--date", default=date.today().isoformat(), help="Date for initial changelog entry")
    parser.add_argument(
        "--project-to",
        default="",
        help="Optional projection targets: codex, claude-code, or a comma-separated list",
    )
    parser.add_argument(
        "--projection-scope",
        default="project",
        choices=["project", "user"],
        help="Projection scope when --project-to is set (default: project)",
    )
    parser.add_argument(
        "--projection-output-root",
        help="Optional base directory for projections when --project-to is set",
    )
    args = parser.parse_args()

    name = normalize_name(args.skill_name)
    display_name = args.display_name or title_case(name)
    categories = parse_csv(args.categories)
    tags = unique_items(parse_csv(args.tags) if args.tags else [name, *categories])
    resources = parse_csv(args.resources)

    root = Path(args.path).expanduser().resolve()
    skill_dir = root / name
    ensure_new_dir(skill_dir)

    (skill_dir / "SKILL.md").write_text(
        SKILL_TEMPLATE.format(name=name, description=args.description, display_name=display_name),
        encoding="utf8",
    )
    (skill_dir / "CHANGELOG.md").write_text(
        CHANGELOG_TEMPLATE.format(version=args.version, date=args.date),
        encoding="utf8",
    )
    write_json(
        skill_dir / "skill.json",
        build_skill_json(
            name=name,
            display_name=display_name,
            description=args.description,
            version=args.version,
            maturity=args.maturity,
            categories=categories,
            author=args.author,
            tags=tags,
        ),
    )

    for resource in resources:
        (skill_dir / resource).mkdir(parents=True, exist_ok=True)

    if args.project_to:
        output_root = (
            Path(args.projection_output_root).expanduser().resolve()
            if args.projection_output_root
            else None
        )
        for platform in parse_platforms(args.project_to):
            destination = projection_dir(
                skill_dir,
                platform,
                args.projection_scope,
                output_root=output_root,
            )
            copy_projection(skill_dir, platform, destination)
            print(f"projected {platform}: {destination}")

    print(skill_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
